postgres:
    database: postgres
    user: postgres
    password: 123
    host: localhost
    port: 5432
    driver: org.postgresql.Driver
    format: jdbc
category_management:
    output_path: ../../category_management_outcome
